# Generated by Django 4.1.5 on 2023-04-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
