# Generated by Django 4.1.5 on 2023-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_custuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
