# Generated by Django 4.1.5 on 2023-04-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_custuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='device',
        ),
    ]
